### ISSUE TITLE
Find good solution for Encrypting and Decrypting

### ISSUE THREAD

**Issue by BelphegorPrime** [BelphegorPrime/lib#1]
I´m not really good at crypto and I think that the solution I found isn´t the best.

If you know some nice and easy to use cryptoalgorithem don´t hesitate, contribute.

**Comment by ghost** [comment]
Maybe I could help you with that, but you should be a little bit more specific then "cryptoalgorithem" ;D.
What do you want to encrypt and decrypt?

**Comment by BelphegorPrime** [comment]
@MyNameNoneOfYourBusiness It´s really nice to have your help.

As you can see the actual implementation gets `[]byte`.
The actual data was a `string` so yeah for a `string` would be great.

Best would be that the solution could easely be used for other programming languages like Javascript, Php, and so on.

**Comment by ghost** [comment]
Okay on work I have  written a library that could help here at least for go. I will look more into this on monday/tuesday.

**Comment by BelphegorPrime** [comment]
@MyNameNoneOfYourBusiness how are you doing? Could you look into this?

**Comment by ghost** [comment]
@BelphegorPrime Yeah sorry I was lately very busy. I cloned the repo and added the new functions within a new branch. But when I try to push it, I have to give it my login credentials but I get this:
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/BelphegorPrime/lib.git/'

you know what I'm doing wrong?

**Comment by ghost** [comment]
I fixed it.... I was in the wrong repo :D

**Comment by BelphegorPrime** [comment]
@MyNameNoneOfYourBusiness nice work 👍 
have a nice day and thanks for your commit :)

**Comment by ghost** [comment]
@BelphegorPrime np and sorry it took a little bit longer. And have a nice day too :D
