### ISSUE TITLE
Write a better readme

### ISSUE THREAD

**Issue by BelphegorPrime** [BelphegorPrime/lib#2]
The readme is very low effort content.

**Comment by abarya** [comment]
Hi @BelphegorPrime,  I'd like to work on this.

**Comment by BelphegorPrime** [comment]
@abhishekarya286 It´s really nice to have your help. 
Feel free to play around with the code and see if you can think up a better readme that captures what it does and how to use it.

**Comment by harsh183** [comment]
I just sent a PR before noticing that this issue existed. https://github.com/BelphegorPrime/lib/pull/3

@BelphegorPrime @abhishekarya286  Accept it if it helps, but otherwise, I agree that the README needs a major overhaul.

**Comment by BelphegorPrime** [comment]
Thanks @harsh183 for your contribution.

**Comment by harsh183** [comment]
It was a small change. @abhishekarya286 the README has been updated, it's not drastic, so you need not incorporate the new changes, but if you haven't, it can be slightly more helpful.

**Comment by BelphegorPrime** [comment]
see pullrequest #4
